-- ==============================================================================
-- DAYFLOW HRMS – SUPABASE DATABASE MIGRATION & INITIAL SCHEMA
-- ==============================================================================

-- 1. Create PROFILES Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  employee_id VARCHAR(30) UNIQUE NOT NULL,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(150),
  phone VARCHAR(20),
  address TEXT,
  job_title VARCHAR(100),
  department VARCHAR(100),
  joining_date DATE DEFAULT CURRENT_DATE,
  profile_picture_url TEXT,
  role VARCHAR(20) NOT NULL DEFAULT 'EMPLOYEE',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT check_role CHECK (role IN ('EMPLOYEE', 'ADMIN'))
);

-- 2. Create ATTENDANCE Table
CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  attendance_date DATE NOT NULL DEFAULT CURRENT_DATE,
  check_in TIMESTAMPTZ,
  check_out TIMESTAMPTZ,
  status VARCHAR(20) DEFAULT 'PRESENT',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT check_attendance_status CHECK (status IN ('PRESENT', 'ABSENT', 'HALF_DAY', 'LEAVE')),
  CONSTRAINT unique_employee_date UNIQUE (employee_id, attendance_date)
);

-- 3. Create LEAVE_REQUESTS Table
CREATE TABLE IF NOT EXISTS public.leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  leave_type VARCHAR(20) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  remarks TEXT,
  status VARCHAR(20) DEFAULT 'PENDING',
  admin_comment TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT check_leave_type CHECK (leave_type IN ('PAID', 'SICK', 'UNPAID')),
  CONSTRAINT check_leave_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

-- 4. Create PAYROLL Table
CREATE TABLE IF NOT EXISTS public.payroll (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE UNIQUE,
  basic_salary NUMERIC(12,2) DEFAULT 0.00,
  allowances NUMERIC(12,2) DEFAULT 0.00,
  deductions NUMERIC(12,2) DEFAULT 0.00,
  net_salary NUMERIC(12,2) DEFAULT 0.00,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- INDEXES FOR PERFORMANCE
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_profiles_employee_id ON public.profiles(employee_id);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);
CREATE INDEX IF NOT EXISTS idx_attendance_employee_id ON public.attendance(employee_id);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON public.attendance(attendance_date);
CREATE INDEX IF NOT EXISTS idx_leave_employee_id ON public.leave_requests(employee_id);
CREATE INDEX IF NOT EXISTS idx_leave_status ON public.leave_requests(status);
CREATE INDEX IF NOT EXISTS idx_payroll_employee_id ON public.payroll(employee_id);

-- ==============================================================================
-- HELPER FUNCTIONS & TRIGGERS
-- ==============================================================================

-- Admin check helper function (SECURITY DEFINER to avoid RLS recursion)
CREATE OR REPLACE FUNCTION public.is_admin(user_uid UUID)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = user_uid AND role = 'ADMIN'
  );
$$;

-- Net salary auto-calculation trigger
CREATE OR REPLACE FUNCTION public.calculate_net_salary()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.net_salary := COALESCE(NEW.basic_salary, 0) + COALESCE(NEW.allowances, 0) - COALESCE(NEW.deductions, 0);
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_calc_payroll_net_salary ON public.payroll;
CREATE TRIGGER trg_calc_payroll_net_salary
BEFORE INSERT OR UPDATE ON public.payroll
FOR EACH ROW
EXECUTE FUNCTION public.calculate_net_salary();

-- Automatic Profile and Default Payroll creation on User Signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_employee_id TEXT;
  v_full_name TEXT;
  v_role TEXT;
  v_phone TEXT;
  v_address TEXT;
  v_department TEXT;
  v_job_title TEXT;
BEGIN
  -- Extract from raw_user_meta_data
  v_employee_id := COALESCE(NEW.raw_user_meta_data->>'employee_id', 'EMP-' || UPPER(SUBSTRING(NEW.id::text FROM 1 FOR 6)));
  v_full_name := COALESCE(NEW.raw_user_meta_data->>'full_name', SPLIT_PART(NEW.email, '@', 1));
  -- Enforce default EMPLOYEE role for public signups unless explicitly set by service role
  v_role := COALESCE(NEW.raw_user_meta_data->>'role', 'EMPLOYEE');
  IF v_role NOT IN ('EMPLOYEE', 'ADMIN') THEN
    v_role := 'EMPLOYEE';
  END IF;

  v_phone := NEW.raw_user_meta_data->>'phone';
  v_address := NEW.raw_user_meta_data->>'address';
  v_department := COALESCE(NEW.raw_user_meta_data->>'department', 'General');
  v_job_title := COALESCE(NEW.raw_user_meta_data->>'job_title', 'Staff Associate');

  -- Insert profile
  INSERT INTO public.profiles (
    id,
    employee_id,
    full_name,
    email,
    phone,
    address,
    job_title,
    department,
    joining_date,
    role
  ) VALUES (
    NEW.id,
    v_employee_id,
    v_full_name,
    NEW.email,
    v_phone,
    v_address,
    v_job_title,
    v_department,
    CURRENT_DATE,
    v_role
  ) ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = COALESCE(EXCLUDED.full_name, public.profiles.full_name);

  -- Insert initial payroll record with default standard figures
  INSERT INTO public.payroll (
    employee_id,
    basic_salary,
    allowances,
    deductions
  ) VALUES (
    NEW.id,
    50000.00,
    5000.00,
    2500.00
  ) ON CONFLICT (employee_id) DO NOTHING;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payroll ENABLE ROW LEVEL SECURITY;

-- 1. PROFILES POLICIES
-- Read: Own profile OR Admin can read all
DROP POLICY IF EXISTS "Users can read own profile or admin reads all" ON public.profiles;
CREATE POLICY "Users can read own profile or admin reads all"
ON public.profiles FOR SELECT
TO authenticated
USING (auth.uid() = id OR public.is_admin(auth.uid()));

-- Update: Employee can update own record, Admin can update any
DROP POLICY IF EXISTS "Users can update own profile or admin updates any" ON public.profiles;
CREATE POLICY "Users can update own profile or admin updates any"
ON public.profiles FOR UPDATE
TO authenticated
USING (auth.uid() = id OR public.is_admin(auth.uid()))
WITH CHECK (auth.uid() = id OR public.is_admin(auth.uid()));

-- Insert: Self or Admin
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile"
ON public.profiles FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = id OR public.is_admin(auth.uid()));

-- 2. ATTENDANCE POLICIES
-- Read: Own attendance OR Admin reads all
DROP POLICY IF EXISTS "Users read own attendance or admin reads all" ON public.attendance;
CREATE POLICY "Users read own attendance or admin reads all"
ON public.attendance FOR SELECT
TO authenticated
USING (employee_id = auth.uid() OR public.is_admin(auth.uid()));

-- Insert: Employee logs own attendance OR Admin inserts
DROP POLICY IF EXISTS "Users can insert own attendance" ON public.attendance;
CREATE POLICY "Users can insert own attendance"
ON public.attendance FOR INSERT
TO authenticated
WITH CHECK (employee_id = auth.uid() OR public.is_admin(auth.uid()));

-- Update: Employee updates own checkout OR Admin updates
DROP POLICY IF EXISTS "Users can update own attendance" ON public.attendance;
CREATE POLICY "Users can update own attendance"
ON public.attendance FOR UPDATE
TO authenticated
USING (employee_id = auth.uid() OR public.is_admin(auth.uid()))
WITH CHECK (employee_id = auth.uid() OR public.is_admin(auth.uid()));

-- Delete: Admin only
DROP POLICY IF EXISTS "Admins can delete attendance" ON public.attendance;
CREATE POLICY "Admins can delete attendance"
ON public.attendance FOR DELETE
TO authenticated
USING (public.is_admin(auth.uid()));

-- 3. LEAVE REQUESTS POLICIES
-- Read: Own leaves OR Admin reads all
DROP POLICY IF EXISTS "Users read own leaves or admin reads all" ON public.leave_requests;
CREATE POLICY "Users read own leaves or admin reads all"
ON public.leave_requests FOR SELECT
TO authenticated
USING (employee_id = auth.uid() OR public.is_admin(auth.uid()));

-- Insert: Employee applies for leave
DROP POLICY IF EXISTS "Users can insert own leave requests" ON public.leave_requests;
CREATE POLICY "Users can insert own leave requests"
ON public.leave_requests FOR INSERT
TO authenticated
WITH CHECK (employee_id = auth.uid() OR public.is_admin(auth.uid()));

-- Update: Admin approves/rejects leaves
DROP POLICY IF EXISTS "Admins can update leave requests" ON public.leave_requests;
CREATE POLICY "Admins can update leave requests"
ON public.leave_requests FOR UPDATE
TO authenticated
USING (public.is_admin(auth.uid()))
WITH CHECK (public.is_admin(auth.uid()));

-- Delete: Own pending leave or Admin
DROP POLICY IF EXISTS "Users can delete own pending leave or admin deletes" ON public.leave_requests;
CREATE POLICY "Users can delete own pending leave or admin deletes"
ON public.leave_requests FOR DELETE
TO authenticated
USING ((employee_id = auth.uid() AND status = 'PENDING') OR public.is_admin(auth.uid()));

-- 4. PAYROLL POLICIES
-- Read: Own payroll OR Admin reads all
DROP POLICY IF EXISTS "Users read own payroll or admin reads all" ON public.payroll;
CREATE POLICY "Users read own payroll or admin reads all"
ON public.payroll FOR SELECT
TO authenticated
USING (employee_id = auth.uid() OR public.is_admin(auth.uid()));

-- Insert: Admin only
DROP POLICY IF EXISTS "Admins can insert payroll" ON public.payroll;
CREATE POLICY "Admins can insert payroll"
ON public.payroll FOR INSERT
TO authenticated
WITH CHECK (public.is_admin(auth.uid()));

-- Update: Admin only
DROP POLICY IF EXISTS "Admins can update payroll" ON public.payroll;
CREATE POLICY "Admins can update payroll"
ON public.payroll FOR UPDATE
TO authenticated
USING (public.is_admin(auth.uid()))
WITH CHECK (public.is_admin(auth.uid()));

-- ==============================================================================
-- 5. STORAGE BUCKET (Avatars)
-- ==============================================================================
-- Create avatars bucket in Supabase storage if not exists
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage Policies
DROP POLICY IF EXISTS "Avatar images are publicly accessible" ON storage.objects;
CREATE POLICY "Avatar images are publicly accessible"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'avatars');

DROP POLICY IF EXISTS "Authenticated users can upload avatars" ON storage.objects;
CREATE POLICY "Authenticated users can upload avatars"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'avatars');

DROP POLICY IF EXISTS "Authenticated users can update own avatars" ON storage.objects;
CREATE POLICY "Authenticated users can update own avatars"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'avatars');

DROP POLICY IF EXISTS "Authenticated users can delete avatars" ON storage.objects;
CREATE POLICY "Authenticated users can delete avatars"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'avatars');

-- ==============================================================================
-- 6. DEMO SEED INSTRUCTIONS (Run after signing up admin and employee)
-- ==============================================================================
-- To promote an account to ADMIN, simply execute:
-- UPDATE public.profiles SET role = 'ADMIN' WHERE email = 'admin@dayflow.com';
